
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextField;

public class AnchorPane extends javax.swing.JPanel {

    private char character;
    private Coordinate coordinate;
    private CoordinateRecorder recorder;
    
    /**
     * Creates new form Test
     */
    public AnchorPane(char _character, CoordinateRecorder _recorder) {
        character = _character;
        recorder = _recorder;
        if (recorder == null) {
            System.out.println("IT'S NULL!");
        }
        System.out.println("Character: " + character);
        initComponents();
    }
    
    public AnchorPane(char _character, CoordinateRecorder _recorder, Coordinate _coordinate) {
    	character = _character;
    	recorder = _recorder;
    	System.out.println("In achor pane constructor");
    	coordinate = _coordinate;
    	initComponents();
    	xTextField.setText(String.valueOf(coordinate.getX()));
    	yTextField.setText(String.valueOf(coordinate.getY()));
    	zTextField.setText(String.valueOf(coordinate.getZ()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void initComponents() {

        letterLabel = new JLabel(Character.toString(character));
        if (character == 'A') {
        	loadButton = new JButton("Load");
        }
        xTextField = new JTextField();
        yTextField = new JTextField();
        zTextField = new JTextField();
        setButton = new JButton();
        hereButton = new JButton();
        hereButton.setEnabled(false);
        
        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 10, 1));

        xTextField.setText("x");
        xTextField.setMinimumSize(new Dimension(100, 20));
        xTextField.setPreferredSize(new Dimension(100, 20));

        yTextField.setText("y");
        yTextField.setMinimumSize(new Dimension(100, 20));
        yTextField.setPreferredSize(new Dimension(100, 20));

        zTextField.setText("z");
        zTextField.setMinimumSize(new Dimension(100, 20));
        zTextField.setPreferredSize(new Dimension(100, 20));

        setButton.setText("Set");
        setButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                setButtonPressed(evt);
            }
        });
        
        hereButton.setText("Here");
        hereButton.addActionListener(new ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hereButtonPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(letterLabel)
            .addComponent(xTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(yTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(zTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(setButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hereButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(letterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setButton)
                    .addComponent(hereButton)))
        );
    }
    
    private void hereButtonPressed(ActionEvent evt) {                                         
        System.out.println("Here button pressed");
        System.out.println("Coordinate X: " + coordinate.getX());
        recorder.atAnchor(character);
    }                                        

    private void setCoordinate(Coordinate _coordinate) {
    	coordinate = _coordinate;
    }
    
    private void setButtonPressed(ActionEvent evt) {
    	System.out.println("Set Button Pressed");
        setAnchor();
        setButton.setEnabled(false);
    }
    
    private void setAnchor() {
    	System.out.println("Set button presed");
    	System.out.println(xTextField.getText());
        coordinate = new Coordinate(Double.parseDouble(xTextField.getText()), Double.parseDouble(yTextField.getText()), Double.parseDouble(zTextField.getText()));
        System.out.println(character);
        System.out.println("After new coordinate");
        recorder.setAnchor(coordinate, character);
        hereButton.setEnabled(true);
        xTextField.setEnabled(false);
        yTextField.setEnabled(false);
        zTextField.setEnabled(false);
    }
    
    // Variables declaration - do not modify                     
    private JButton setButton;
    private JButton hereButton;
    private JButton loadButton;
    private JLabel letterLabel;
    private JTextField xTextField;
    private JTextField yTextField;
    private JTextField zTextField;
    // End of variables declaration                   
}
